FROM node:22-alpine

WORKDIR /app
 
RUN apk add --no-cache \
    python3 \
    py3-setuptools \
    make \
    g++ \
    sqlite

COPY package*.json ./

RUN rm -rf node_modules

# Forçar download de binários pré-compilados
RUN npm install --prefer-offline --no-audit

COPY . .

EXPOSE 5176

CMD [ "npm", "run", "dev" ]