services:
  db:
    image: postgres:alpine
    container_name: norddev_note_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5441:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: 
      context: .
      dockerfile: Dockerfile.proda
    container_name: norddev_note
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db    

volumes:
  postgres-data: