services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app_norddev_note
    environment:
      - NODE_ENV=development
    ports:
      - "5176:5176"
    volumes:
      - .:/app
      - /app/node_modules  

